// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJpo4VetzY2L7K2kheu-H-I5JUA928Vk',
    appId: '1:255352916458:web:36713f833148393be2ca93',
    messagingSenderId: '255352916458',
    projectId: 'journeyrecorded-fff2b',
    authDomain: 'journeyrecorded-fff2b.firebaseapp.com',
    storageBucket: 'journeyrecorded-fff2b.appspot.com',
    measurementId: 'G-4N71STX9ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrlNAAERcIjqbF8DZnZFv3IEaCc-TsGfk',
    appId: '1:255352916458:android:79e1466e2728440ae2ca93',
    messagingSenderId: '255352916458',
    projectId: 'journeyrecorded-fff2b',
    storageBucket: 'journeyrecorded-fff2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV6SBI_4vB6QzWpr9QOVsoBc6ACsTGbj0',
    appId: '1:255352916458:ios:07eb1573450f16e7e2ca93',
    messagingSenderId: '255352916458',
    projectId: 'journeyrecorded-fff2b',
    storageBucket: 'journeyrecorded-fff2b.appspot.com',
    iosBundleId: 'com.evs.jr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV6SBI_4vB6QzWpr9QOVsoBc6ACsTGbj0',
    appId: '1:255352916458:ios:c91ff64a31b63d66e2ca93',
    messagingSenderId: '255352916458',
    projectId: 'journeyrecorded-fff2b',
    storageBucket: 'journeyrecorded-fff2b.appspot.com',
    iosBundleId: 'com.example.journeyRecorded',
  );
}
